// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnB4LQGlutTz-t2sCHQjFM06JyYY4xy8',
    appId: '1:967268707658:web:63d4c8bf9ab759a16265b3',
    messagingSenderId: '967268707658',
    projectId: 'sharelane-b3173',
    authDomain: 'sharelane-b3173.firebaseapp.com',
    storageBucket: 'sharelane-b3173.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDTXx3gjKvod4XWyelPzqNNbsXBVlRrM',
    appId: '1:967268707658:android:b644e5cea21c60f56265b3',
    messagingSenderId: '967268707658',
    projectId: 'sharelane-b3173',
    storageBucket: 'sharelane-b3173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFXbY6FVITRwx5x1RZ5Q6tU1ac1ciQFg',
    appId: '1:967268707658:ios:23315a375ab3fadf6265b3',
    messagingSenderId: '967268707658',
    projectId: 'sharelane-b3173',
    storageBucket: 'sharelane-b3173.firebasestorage.app',
    iosBundleId: 'com.carlisting.carListingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmFXbY6FVITRwx5x1RZ5Q6tU1ac1ciQFg',
    appId: '1:967268707658:ios:23315a375ab3fadf6265b3',
    messagingSenderId: '967268707658',
    projectId: 'sharelane-b3173',
    storageBucket: 'sharelane-b3173.firebasestorage.app',
    iosBundleId: 'com.carlisting.carListingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsnB4LQGlutTz-t2sCHQjFM06JyYY4xy8',
    appId: '1:967268707658:web:b385984026a912236265b3',
    messagingSenderId: '967268707658',
    projectId: 'sharelane-b3173',
    authDomain: 'sharelane-b3173.firebaseapp.com',
    storageBucket: 'sharelane-b3173.firebasestorage.app',
  );
}
